steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-docker.pkg.dev/igneous-thunder-410709/eu.gcr.io/bcs-trainer', '-f', 'dockerfiles/train_model.dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-docker.pkg.dev/igneous-thunder-410709/eu.gcr.io/bcs-trainer']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-docker.pkg.dev/igneous-thunder-410709/eu.gcr.io/bcs-prediction-api', '-f', 'dockerfiles/predict_model.dockerfile', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-docker.pkg.dev/igneous-thunder-410709/eu.gcr.io//bcs-prediction-api' ]