traindata_len: 5
valdata_len: 3
testdata_len: 0
train_img_location: "./tests/trainer/test-data/train/"
train_mask_location: "./tests/trainer/test-data/train_mask/"
validation_img_location: "./tests/trainer/test-data/val/"
validation_mask_location: "./tests/trainer/test-data/val_mask/"
test_location: "./tests/trainer/test-data/tst/"
