spatial_dims: 2
in_channels: 3
out_channels: 3
channels: [16, 32, 64, 128, 256]
strides: [2, 2, 2, 2]
num_res_units: 2
dropout: 0.0
activation: "PRELU"
kernel_size: 3.0
up_kernel_size: 3.0
model: "UNet"
