max_epochs: 10
limit_train_batches: 0.4
learning_rate: 0.001
training_batch_size: 16
training_num_workers: 4
validation_batch_size: 16
validation_num_workers: 4
train_img_location: "./data/raw/BCSS_512/train_512/"
train_mask_location: "./data/raw/BCSS_512/train_mask_512/"
validation_img_location: "./data/raw/BCSS_512/val_512/"
validation_mask_location: "./data/raw/BCSS_512/val_mask_512/"
test_location: "./data/raw/BCSS/test/"
wandb_enabled: True
model_repo_location: "./models"
optimizer: "AdamW"
