workerPoolSpecs:
    machineSpec:
        machineType: n2-standard-4
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/igneous-thunder-410709/bcs-trainer
        args: ["train_hyp=train_hyp_gcp_cpu"]
