workerPoolSpecs:
    machineSpec:
        machineType: n2-standard-4
    replicaCount: 1
    containerSpec:
        imageUri: europe-docker.pkg.dev/igneous-thunder-410709/eu.gcr.io/bcs-trainer:latest
        args: ["train_hyp=train_hyp_gcp_cpu"]
