resources:
  dataset:
    train_img_location: "./data/raw/BCSS/train/"
    train_mask_location: "./data/raw/BCSS/train_mask/"
    validation_img_location: "./data/raw/BCSS/val/"
    validation_mask_location: "./data/raw/BCSS/val_mask/"
    test_location: "./data/raw/BCSS/test/"
experiments:
  - test1
