name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Test with pytest
      run: |
        pytest ./tests

  docker-build-train-test:
    runs-on: ubuntu-latest
    needs: [ unit-testing ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Building Train container
      run: |
        docker build -t breast-cancer-segmentation:latest -f dockerfiles/train_model.dockerfile .
